# Generated by Django 4.2.10 on 2024-02-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Color', models.CharField(max_length=20)),
                ('Company', models.CharField(max_length=20)),
                ('Rate', models.IntegerField()),
                ('Description', models.TextField()),
            ],
        ),
    ]
