# Generated by Django 4.2.10 on 2024-02-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0006_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='CarName',
            field=models.CharField(default='default', max_length=20),
        ),
    ]
